services:
  - type: web
    name: savdo
    runtime: node
    plan: free
    buildCommand: "node -v"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: PORT
        value: "4173"
